server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydate?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: root
    password: root
  application:
    name: qxmxzwwgroup
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
    instance-id: ${hostname}:${server.port}  #向注册中心暴露服务提供者的IP和端口
    prefer-ip-address: true
#在控制台打印MySQL日志
logging:
  level:
    com:
      qsmx:
        zww:
          mapper: debug
#logging.level.自己的mapper包=日志级别