server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydata?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    #url: jdbc:mysql://*******:3306/feather?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=UTC //导数的时候配的地址
    username: root
    password: root
  application:
    name: qxmxzwwgroup
  data:
    mongodb:
      host: localhost
      port: 27017
      database: data
      # username:
      # password:
  #测试同时连接多个redis集群配置
  redis:
    host: localhost  #导数测试redis
    password:
    port: 6379
    cache1:
      cluster:
        nodes: localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379
    cache2:
      cluster:
        nodes: localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379
    cache3:
      cluster:
        nodes: localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: 3ms
    database: 0

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
    instance-id: ${hostname}:${server.port}  #向注册中心暴露服务提供者的IP和端口
    prefer-ip-address: true
#在控制台打印MySQL日志
logging:
  level:
    com:
      qsmx:
        zww:
          mapper: debug
#在控制台打印mongo日志
    org:
      springframework:
        data:
          mongodb:
            core: debug

#redis配置

#logging.level.自己的mapper包=日志级别

#钉钉机器人的token练剑
dingDingRobotUrl: https://oapi.dingtalk.com/robot/send?access_token=81e84c99e81083deb6a99b5fa08678725f5b4e3f7ecae4a010d47ebc5e983072